name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Prepare gtest
      run: |
        mkdir build
        cd build
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - name: Run cmake build
      run: |
        cd build
        cmake .. -DBUILD_TESTS=ON
        make
    - name: Run unit tests
      run: |
        cd build
        ./ALL_TEST

